name: dask-kubernetes-test
channels:
  - defaults
  - conda-forge
dependencies:
  - flake8
  - ipywidgets
  - dask=1.1.1
  - distributed=1.25.3
  - nomkl
  - pytest
  - python=3.6
  - pyyaml
  - pip:
    - kubernetes==6
    - kubernetes-asyncio
    - pytest-asyncio
