name: dask-kubernetes-test
channels:
  - defaults
  - conda-forge
dependencies:
  - flake8
  - ipywidgets
  - dask=1.1.0
  - distributed=1.25.2
  - nomkl
  - pytest
  - python=3.6
  - pyyaml
  - pip:
    - kubernetes==6
    - kubernetes-asyncio
    - git+https://github.com/dask/distributed@master
